name: CCDiary
options:
  bundleIdPrefix: sh.saqoo
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.6.0"
    CURRENT_PROJECT_VERSION: "13"
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  CCDiary:
    type: application
    platform: macOS
    sources:
      - path: Sources/CCDiary
        excludes:
          - "**/.DS_Store"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: sh.saqoo.CCDiary
      PRODUCT_NAME: CCDiary
      INFOPLIST_FILE: Sources/CCDiary/Info.plist
      GENERATE_INFOPLIST_FILE: false
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: G5G54TCH8W
      ENABLE_HARDENED_RUNTIME: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
    info:
      path: Sources/CCDiary/Info.plist
      properties:
        CFBundleName: CCDiary
        CFBundleDisplayName: CCDiary
        CFBundleIdentifier: sh.saqoo.CCDiary
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: CCDiary
        LSMinimumSystemVersion: "14.0"
        NSHighResolutionCapable: true
        LSApplicationCategoryType: public.app-category.developer-tools
        NSHumanReadableCopyright: "© 2026 Saqoosha. MIT License."

  benchmark:
    type: tool
    platform: macOS
    sources:
      - path: Tools/Benchmark
      - path: Sources/CCDiary/Services
      - path: Sources/CCDiary/Models
    settings:
      PRODUCT_NAME: benchmark
      PRODUCT_MODULE_NAME: BenchmarkTool

  cursor-test:
    type: tool
    platform: macOS
    sources:
      - path: Tools/CursorTest
    settings:
      PRODUCT_NAME: cursor-test
      PRODUCT_MODULE_NAME: CursorTestTool
