import Foundation

/// Converts CCDiary markdown into a Slack `chat.postMessage` payload.
///
/// Slack's mrkdwn does not render `# ## ###` headings or `**bold**`, so the raw
/// diary markdown shows up with literal `#` and `**` characters in chat. This
/// builder emits Block Kit blocks (header + sections + context) and rewrites
/// inline markdown into Slack mrkdwn (`*bold*`, `<url|label>`).
enum SlackMessageBuilder {
    /// Slack's per-section text limit is 3000 chars; leave a small buffer.
    static let maxSectionLength = 2900
    /// Slack accepts up to 50 blocks; reserve a few for header + context + truncation note.
    static let maxBlocks = 45

    struct Output {
        let blocks: [[String: Any]]
        /// Notification fallback shown in push/sidebar previews.
        let fallbackText: String
        /// True when content was truncated to fit Slack's limits.
        let truncated: Bool
    }

    static func build(from entry: DiaryEntry) -> Output {
        build(markdown: entry.markdown, dateString: entry.dateString)
    }

    static func build(markdown: String, dateString: String) -> Output {
        let trimmed = markdown.trimmingCharacters(in: .whitespacesAndNewlines)
        let (headerText, bodyMarkdown) = splitHeaderAndBody(trimmed)
        let body = stripFooter(bodyMarkdown).trimmingCharacters(in: .whitespacesAndNewlines)

        var chunks: [String] = []
        for section in splitByH2(body) {
            let mrkdwn = convertToMrkdwn(section).trimmingCharacters(in: .whitespacesAndNewlines)
            guard !mrkdwn.isEmpty else { continue }
            if mrkdwn.count <= maxSectionLength {
                chunks.append(mrkdwn)
            } else {
                chunks.append(contentsOf: hardSplit(mrkdwn, maxLength: maxSectionLength))
            }
        }

        var truncated = false
        if chunks.count > maxBlocks {
            chunks = Array(chunks.prefix(maxBlocks))
            truncated = true
        }

        let resolvedHeader = headerText?.isEmpty == false ? headerText! : dateString
        var blocks: [[String: Any]] = [[
            "type": "header",
            "text": [
                "type": "plain_text",
                "text": String(resolvedHeader.prefix(150)),
                "emoji": true
            ]
        ]]
        for sectionText in chunks {
            blocks.append([
                "type": "section",
                "text": ["type": "mrkdwn", "text": sectionText]
            ])
        }
        if truncated {
            blocks.append([
                "type": "context",
                "elements": [["type": "mrkdwn", "text": ":warning: _Truncated to fit Slack limits._"]]
            ])
        }
        blocks.append([
            "type": "context",
            "elements": [["type": "mrkdwn", "text": "_Generated by CCDiary_"]]
        ])

        return Output(
            blocks: blocks,
            fallbackText: "\(resolvedHeader) — CCDiary",
            truncated: truncated
        )
    }

    // MARK: - Markdown parsing

    static func splitHeaderAndBody(_ markdown: String) -> (header: String?, body: String) {
        var lines = markdown.components(separatedBy: "\n")
        guard let first = lines.first, first.hasPrefix("# ") else {
            return (nil, markdown)
        }
        let header = String(first.dropFirst(2)).trimmingCharacters(in: .whitespaces)
        lines.removeFirst()
        while let next = lines.first, next.trimmingCharacters(in: .whitespaces).isEmpty {
            lines.removeFirst()
        }
        return (header.isEmpty ? nil : header, lines.joined(separator: "\n"))
    }

    /// Drop the trailing `---\n\nGenerated by CCDiary` footer so the builder can
    /// place it in a context block instead of inline.
    static func stripFooter(_ markdown: String) -> String {
        let lines = markdown.components(separatedBy: "\n")
        guard let dividerIdx = lines.lastIndex(of: "---") else {
            return markdown
        }
        return lines[..<dividerIdx].joined(separator: "\n")
    }

    /// Group the body into one chunk per `## ` heading. Pre-H2 prose (rare for
    /// CCDiary output) becomes the first chunk.
    static func splitByH2(_ markdown: String) -> [String] {
        let lines = markdown.components(separatedBy: "\n")
        var sections: [[String]] = [[]]
        for line in lines {
            if line.hasPrefix("## "), !(sections.last?.isEmpty ?? true) {
                sections.append([line])
            } else {
                sections[sections.count - 1].append(line)
            }
        }
        return sections.map { $0.joined(separator: "\n") }
    }

    // MARK: - Mrkdwn conversion

    /// Convert CCDiary markdown to Slack mrkdwn. Only handles constructs
    /// `DiaryFormatter` actually emits; other inline syntax (backticks, dash
    /// lists, blockquotes) renders identically in Slack mrkdwn.
    static func convertToMrkdwn(_ markdown: String) -> String {
        var text = markdown
            .components(separatedBy: "\n")
            .map(convertHeadingLine)
            .joined(separator: "\n")

        // **bold** -> *bold*
        text = text.replacingOccurrences(
            of: #"\*\*([^*\n]+?)\*\*"#,
            with: "*$1*",
            options: .regularExpression
        )

        // [label](url) -> <url|label>
        text = text.replacingOccurrences(
            of: #"\[([^\]]+)\]\(([^)\s]+)\)"#,
            with: "<$2|$1>",
            options: .regularExpression
        )

        return text
    }

    private static func convertHeadingLine(_ line: String) -> String {
        for prefix in ["### ", "## ", "# "] {
            if line.hasPrefix(prefix) {
                let body = line.dropFirst(prefix.count).trimmingCharacters(in: .whitespaces)
                return body.isEmpty ? "" : "*\(body)*"
            }
        }
        return line
    }

    // MARK: - Chunking

    /// Split a too-large block by line boundaries, falling back to a hard
    /// character cut for pathologically long single lines.
    private static func hardSplit(_ text: String, maxLength: Int) -> [String] {
        let lines = text.components(separatedBy: "\n")
        var chunks: [String] = []
        var current = ""
        for line in lines {
            let candidate = current.isEmpty ? line : current + "\n" + line
            if candidate.count > maxLength {
                if !current.isEmpty {
                    chunks.append(current)
                    current = ""
                }
                if line.count > maxLength {
                    var remaining = Substring(line)
                    while remaining.count > maxLength {
                        let cut = remaining.index(remaining.startIndex, offsetBy: maxLength)
                        chunks.append(String(remaining[..<cut]))
                        remaining = remaining[cut...]
                    }
                    current = String(remaining)
                } else {
                    current = line
                }
            } else {
                current = candidate
            }
        }
        if !current.isEmpty {
            chunks.append(current)
        }
        return chunks
    }
}
