import Foundation

/// Converts CCDiary markdown into a Slack `chat.postMessage` payload.
///
/// Slack's mrkdwn does not render `# ## ###` headings or `**bold**`, so the raw
/// diary markdown shows up with literal `#` and `**` characters in chat. This
/// builder emits Block Kit blocks (header + sections + context) and rewrites
/// inline markdown into Slack mrkdwn (`*bold*`, `<url|label>`).
enum SlackMessageBuilder {
    // Slack Block Kit limits — see https://docs.slack.dev/reference/block-kit/blocks/
    private static let slackBlockLimit = 50
    private static let slackSectionTextLimit = 3000
    private static let slackHeaderTextLimit = 150

    /// Per-section text budget. We leave a 100-char buffer under Slack's
    /// 3000-char limit to be safe against any counting differences.
    static let maxSectionLength = slackSectionTextLimit - 100
    /// Reserved for header (1) + footer context (1) + truncation context (1) + safety (2).
    private static let reservedBlocks = 5
    /// Maximum number of content section blocks before we truncate.
    static let maxBlocks = slackBlockLimit - reservedBlocks

    private static let footerMarker = "Generated by CCDiary"

    struct Output {
        let blocks: [[String: Any]]
        /// Notification fallback shown in push/sidebar previews.
        let fallbackText: String
        let truncated: Bool
    }

    static func build(from entry: DiaryEntry) -> Output {
        build(markdown: entry.markdown, dateString: entry.dateString)
    }

    static func build(markdown: String, dateString: String) -> Output {
        let trimmed = markdown.trimmingCharacters(in: .whitespacesAndNewlines)
        let (headerText, bodyMarkdown) = splitHeaderAndBody(trimmed)
        let body = stripFooter(bodyMarkdown).trimmingCharacters(in: .whitespacesAndNewlines)

        var chunks: [String] = []
        var truncated = false
        for section in splitByH2(body) {
            let mrkdwn = convertToMrkdwn(section).trimmingCharacters(in: .whitespacesAndNewlines)
            guard !mrkdwn.isEmpty else { continue }
            if mrkdwn.utf16.count <= maxSectionLength {
                chunks.append(mrkdwn)
            } else {
                for chunk in hardSplit(mrkdwn, maxLength: maxSectionLength) {
                    if chunk.utf16.count <= slackSectionTextLimit {
                        chunks.append(chunk)
                    } else {
                        // Pathological grapheme wider than Slack's per-section
                        // hard limit (3000 UTF-16 units). Drop the chunk and
                        // flag so the CLI surfaces a truncation warning rather
                        // than letting Slack reject the whole post.
                        truncated = true
                    }
                }
            }
        }

        if chunks.count > maxBlocks {
            chunks = Array(chunks.prefix(maxBlocks))
            truncated = true
        }

        let resolvedHeader = headerText.flatMap { $0.isEmpty ? nil : $0 } ?? dateString
        var blocks: [[String: Any]] = [[
            "type": "header",
            "text": [
                "type": "plain_text",
                "text": String(resolvedHeader.prefix(slackHeaderTextLimit)),
                "emoji": true
            ]
        ]]
        for sectionText in chunks {
            blocks.append([
                "type": "section",
                "text": ["type": "mrkdwn", "text": sectionText]
            ])
        }
        if truncated {
            blocks.append([
                "type": "context",
                "elements": [["type": "mrkdwn", "text": ":warning: _Truncated to fit Slack limits._"]]
            ])
        }
        blocks.append([
            "type": "context",
            "elements": [["type": "mrkdwn", "text": "_Generated by CCDiary_"]]
        ])

        return Output(
            blocks: blocks,
            fallbackText: "\(resolvedHeader) — CCDiary",
            truncated: truncated
        )
    }

    // MARK: - Markdown parsing

    private static func splitHeaderAndBody(_ markdown: String) -> (header: String?, body: String) {
        var lines = markdown.components(separatedBy: "\n")
        guard let first = lines.first, first.hasPrefix("# ") else {
            return (nil, markdown)
        }
        let header = String(first.dropFirst(2)).trimmingCharacters(in: .whitespaces)
        lines.removeFirst()
        while let next = lines.first, next.trimmingCharacters(in: .whitespaces).isEmpty {
            lines.removeFirst()
        }
        return (header.isEmpty ? nil : header, lines.joined(separator: "\n"))
    }

    /// Drop the trailing `---\n\nGenerated by CCDiary` footer so the builder can
    /// place it in a context block instead of inline.
    ///
    /// We require the divider to be followed (after blank lines) by a line
    /// containing the footer marker, so a `---` horizontal rule used inside the
    /// diary body doesn't silently truncate real content.
    private static func stripFooter(_ markdown: String) -> String {
        let lines = markdown.components(separatedBy: "\n")
        for index in lines.indices.reversed() where lines[index] == "---" {
            if let next = lines[(index + 1)...].first(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty }),
               next.contains(footerMarker) {
                return lines[..<index].joined(separator: "\n")
            }
        }
        return markdown
    }

    /// Group the body into one chunk per `## ` heading. Pre-H2 prose (rare for
    /// CCDiary output) becomes the first chunk.
    private static func splitByH2(_ markdown: String) -> [String] {
        let lines = markdown.components(separatedBy: "\n")
        var sections: [[String]] = [[]]
        for line in lines {
            if line.hasPrefix("## "), !(sections.last?.isEmpty ?? true) {
                sections.append([line])
            } else {
                sections[sections.count - 1].append(line)
            }
        }
        return sections.map { $0.joined(separator: "\n") }
    }

    // MARK: - Mrkdwn conversion

    /// Convert CCDiary markdown to Slack mrkdwn. Only handles constructs
    /// `DiaryFormatter` actually emits; other inline syntax (backticks, dash
    /// lists, blockquotes) renders identically in Slack mrkdwn.
    private static func convertToMrkdwn(_ markdown: String) -> String {
        var text = markdown
            .components(separatedBy: "\n")
            .map(convertHeadingLine)
            .joined(separator: "\n")

        // ***bold-italic*** -> *_bold-italic_* (process before ** to avoid leaving stray *)
        text = text.replacingOccurrences(
            of: #"\*\*\*([^*\n]+?)\*\*\*"#,
            with: "*_$1_*",
            options: .regularExpression
        )

        // **bold** -> *bold*
        text = text.replacingOccurrences(
            of: #"\*\*([^*\n]+?)\*\*"#,
            with: "*$1*",
            options: .regularExpression
        )

        // Slack's mrkdwn parser only recognizes inline code spans when the
        // backticks sit on a word boundary. Japanese characters don't qualify,
        // so `メモ化、`admin.ts`の防御的` renders with literal backticks. Pad
        // adjacent code spans with spaces (skipping cases where a bracket or
        // sentence-final punctuation already serves as the boundary).
        text = padCodeSpans(text)

        // Convert markdown links into Slack `<url|label>` link constructs while
        // escaping Slack's three special characters (`& < >`) in the
        // surrounding plain text. Escaping has to happen here — applied
        // earlier it would mangle URLs (e.g. `?a=b&c` → `?a=b&amp;c`),
        // applied later it would corrupt the link constructs we just emitted.
        return convertLinksAndEscape(text)
    }

    private static let codeSpanRegex = try! NSRegularExpression(pattern: #"`[^`\n]+?`"#)
    private static let codeSpanOpeners = CharacterSet(charactersIn: " \t\n([{<（「『【〈《")
    private static let codeSpanClosers = CharacterSet(charactersIn: " \t\n)]}>.,;:!?。、！？）」』】〉》")

    private static func padCodeSpans(_ text: String) -> String {
        let ns = text as NSString
        let fullRange = NSRange(location: 0, length: ns.length)
        let matches = codeSpanRegex.matches(in: text, range: fullRange)
        guard !matches.isEmpty else { return text }

        // Slack doesn't render mrkdwn inside `<url|label>` link labels, so
        // padding code spans that live inside `[label](url)` only adds noise
        // and leaves bare backticks. Skip those spans here.
        let linkRanges = linkRegex.matches(in: text, range: fullRange).map(\.range)

        // Use a Set so adjacent code spans (`a``b`) don't double-insert at
        // the same UTF-16 position. Sort descending and apply so earlier
        // indices stay valid as we mutate from the tail.
        var insertions: Set<Int> = []
        for match in matches {
            if linkRanges.contains(where: { NSIntersectionRange($0, match.range).length > 0 }) {
                continue
            }
            let start = match.range.location
            let end = start + match.range.length
            if start > 0 {
                let unit = ns.character(at: start - 1)
                // Surrogate halves return nil from Unicode.Scalar(_: UInt16).
                // Treat them as non-boundary characters (e.g. emoji like 🎉)
                // so adjacent code spans still get padded.
                let isOpener = Unicode.Scalar(unit).map(codeSpanOpeners.contains) ?? false
                if !isOpener {
                    insertions.insert(start)
                }
            }
            if end < ns.length {
                let unit = ns.character(at: end)
                let isCloser = Unicode.Scalar(unit).map(codeSpanClosers.contains) ?? false
                if !isCloser {
                    insertions.insert(end)
                }
            }
        }
        guard !insertions.isEmpty else { return text }

        let result = NSMutableString(string: text)
        for position in insertions.sorted(by: >) {
            result.insert(" ", at: position)
        }
        return result as String
    }

    /// Match `[label](url)` allowing one level of balanced `()` inside the URL
    /// (so e.g. Wikipedia links render correctly). The URL fragment is either
    /// any non-paren/whitespace char OR a balanced `(...)` group.
    private static let linkRegex = try! NSRegularExpression(
        pattern: #"\[([^\]\n]+)\]\(((?:[^()\s]|\([^()]*\))+)\)"#
    )

    private static func convertLinksAndEscape(_ text: String) -> String {
        let ns = text as NSString
        let matches = linkRegex.matches(in: text, range: NSRange(location: 0, length: ns.length))
        var result = ""
        var cursor = 0
        for match in matches {
            let preRange = NSRange(location: cursor, length: match.range.location - cursor)
            result += escapeMrkdwn(ns.substring(with: preRange))
            let label = ns.substring(with: match.range(at: 1))
            let url = ns.substring(with: match.range(at: 2))
            // Inside the link, only `<` `>` `&` would break the construct;
            // escape them too so the resulting Slack link parses cleanly.
            result += "<\(escapeMrkdwn(url))|\(escapeMrkdwn(label))>"
            cursor = match.range.location + match.range.length
        }
        if cursor < ns.length {
            let tailRange = NSRange(location: cursor, length: ns.length - cursor)
            result += escapeMrkdwn(ns.substring(with: tailRange))
        }
        return result
    }

    /// Slack's three required mrkdwn escapes (in order: `&` first to avoid
    /// double-escaping introduced `&` chars).
    private static func escapeMrkdwn(_ text: String) -> String {
        text
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
    }

    private static func convertHeadingLine(_ line: String) -> String {
        for prefix in ["###### ", "##### ", "#### ", "### ", "## ", "# "] {
            if line.hasPrefix(prefix) {
                let body = line.dropFirst(prefix.count).trimmingCharacters(in: .whitespaces)
                return body.isEmpty ? "" : "*\(body)*"
            }
        }
        return line
    }

    // MARK: - Chunking

    /// Split a too-large block by line boundaries, falling back to a hard
    /// character cut for pathologically long single lines. Length is measured
    /// in UTF-16 code units to match Slack's section-text accounting.
    private static func hardSplit(_ text: String, maxLength: Int) -> [String] {
        let lines = text.components(separatedBy: "\n")
        var chunks: [String] = []
        var current = ""
        for line in lines {
            let candidate = current.isEmpty ? line : current + "\n" + line
            if candidate.utf16.count > maxLength {
                if !current.isEmpty {
                    chunks.append(current)
                    current = ""
                }
                if line.utf16.count > maxLength {
                    var remaining = Substring(line)
                    while remaining.utf16.count > maxLength {
                        guard let cut = utf16Cut(remaining, maxLength: maxLength) else {
                            // Single grapheme cluster wider than maxLength
                            // UTF-16 units (pathological — never seen in real
                            // diaries). Emit it as one chunk rather than
                            // splitting the grapheme; the caller in `build()`
                            // checks each chunk against Slack's hard limit and
                            // drops + flags any that still overflow.
                            chunks.append(String(remaining))
                            remaining = remaining[remaining.endIndex...]
                            break
                        }
                        chunks.append(String(remaining[..<cut]))
                        remaining = remaining[cut...]
                    }
                    current = String(remaining)
                } else {
                    current = line
                }
            } else {
                current = candidate
            }
        }
        if !current.isEmpty {
            chunks.append(current)
        }
        return chunks
    }

    /// Largest prefix of `s` whose UTF-16 length is `≤ maxLength` and which
    /// ends on a grapheme-cluster boundary. Returns `nil` when even the first
    /// Character is wider than `maxLength` UTF-16 units.
    private static func utf16Cut(_ s: Substring, maxLength: Int) -> Substring.Index? {
        var consumed = 0
        var cut = s.startIndex
        for char in s {
            let width = char.utf16.count
            if consumed + width > maxLength { break }
            consumed += width
            cut = s.index(after: cut)
        }
        return cut == s.startIndex ? nil : cut
    }
}
